### ISSUE TITLE
Enable Line Numbers for Code Snippets

### ISSUE THREAD

**Issue by nearmint** [TheOdinProject/theodinproject#1054]
In the TOP lessons, code snippets are frequently referred to by line number. This is currently inconvenient, because line numbers are not shown. 

As far as I know we use kramdown for markdown conversion. And I found a potential solution to enable line numbers here: https://github.com/jekyll/jekyll/issues/4619 
```
kramdown:
    syntax_highlighter_opts:
        block:
            line_numbers: true
```

I have a setup of TOP locally, but I don't know where to insert that code.
