### ISSUE TITLE
Feature: Automate adding issues to project board

### ISSUE THREAD

**Issue by ChargrilledChook** [TheOdinProject/theodinproject#3092]
As a maintainer, I would like to automate adding issues to the project board, so that we spend less time manually managing it.

This can be easily achieved by using an official GitHub action:

```yml
name: Add issues to project  

on:
  issues:
    types:
      - opened
      - transferred

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.1.0
        with:
          project-url: https://github.com/orgs/TheOdinProject/projects/12 # Main site board
          github-token: ${{ secrets.PROJECT_SECRET }} # Placeholder name
```
The only prerequisite is a [PAT that has repo and project permissions](https://github.com/marketplace/actions/add-to-github-projects#inputs).

**Notes**

- This is a planned native feature for projects, but this is a nice workaround until it's released.

- This version will automatically add any issues that are opened or transferred to the board, but it can also be configured to consider labels and / or pull requests (ie "only add pull requests with the `needs review` OR `bug` labels").

- [Page for the action](https://github.com/marketplace/actions/add-to-github-projects)
